image: gitpod/workspace-full

tasks:
  - init: |
      git config --global user.email "169752319+circleds-quare@users.noreply.github.com"
      git config --global user.name "circleds-quare"
      sudo apt update
      sudo apt install -y curl unzip xz-utils zip libglu1-mesa default-jdk
      curl -O https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.22.0-stable.tar.xz
      tar xf flutter_linux_3.22.0-stable.tar.xz
      echo 'export PATH="$PATH:/workspace/flutter/bin"' >> ~/.bashrc
      source ~/.bashrc
      flutter doctor
  - command: |
      export PATH="$PATH:/workspace/flutter/bin"
      flutter pub get
